/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                name: string;
                                /** Format: date-time */
                                created_at: string;
                            }[];
                            next_cursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        name: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** Format: date-time */
                            created_at: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** Format: date-time */
                            created_at: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token: string;
                            refresh_token: string;
                            token_type: string;
                            expires_in: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token: string;
                            refresh_token: string;
                            token_type: string;
                            expires_in: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                author_id?: string | null;
                                author_name?: string | null;
                                title: string;
                                body: string;
                                /** Format: date-time */
                                created_at: string;
                                version: number;
                            }[];
                            next_cursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title: string;
                        body: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            author_id?: string | null;
                            author_name?: string | null;
                            title: string;
                            body: string;
                            /** Format: date-time */
                            created_at: string;
                            version: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        body?: string;
                        version: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            author_id?: string | null;
                            author_name?: string | null;
                            title: string;
                            body: string;
                            /** Format: date-time */
                            created_at: string;
                            version: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                /** @enum {string} */
                                code: "bad_request" | "unauthenticated" | "unauthorized" | "not_found" | "conflict" | "unprocessable_entity" | "rate_limited" | "internal_error" | "validation_failed" | "idempotency_key_required" | "request_in_progress" | "idempotency_key_reused" | "pagination.cursor_mismatch" | "users.not_found" | "users.email_taken" | "users.invalid_credentials" | "users.invalid_refresh_token" | "posts.not_found" | "posts.version_conflict";
                                message: string;
                                request_id: string;
                                details?: unknown;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
